/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Claculator2;
import com.fazecast.jSerialComm.*;
import java.awt.Dimension;
import java.io.InputStream;
import java.util.*;

/**
 *
 * @author Admin
 */
public class GUI extends javax.swing.JFrame {

    private Calculator calc;
    private String temp;
    private String [] numberPad = {"0","1","2","3","4","5","6","7","8","9","."};
    private String [] opPad = {"+","-","*","/","="};
    private String [] specialConst = {"3.14159265359"};
    private String [] specialOp = {"sqr", "sqrt", "percent"};
    private String mode = "standard";
    private Serial printer;
    private String [] ports;
    private int selectedPort;
    private int baudRate;
    private Dimension window, windowCom, comBox;
    Thread thread2;
    InputStream input;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        printer = new Serial();
//        thread2 = new Thread(printer);
        
        ports = printer.getPortsAsStrings();
        baudRate = 115200;
        
        window = new Dimension(415,560);
        windowCom = new Dimension(415,680);
        comBox = new Dimension(350,430);
        initComponents();
        temp = "";
        calc = new Calculator();
        memDisplay.setText("");
        calcDisplay.setText("0");
        gCode.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcDisplay = new javax.swing.JTextField();
        memDisplay = new javax.swing.JTextField();
        bBack = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bChange = new javax.swing.JButton();
        standard = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bPlus = new javax.swing.JButton();
        bSqrt = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bSub = new javax.swing.JButton();
        bSqr = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bMulti = new javax.swing.JButton();
        bPercent = new javax.swing.JButton();
        bKomm = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bOp = new javax.swing.JButton();
        bDiv = new javax.swing.JButton();
        bPi = new javax.swing.JButton();
        gCode = new javax.swing.JPanel();
        tInPut = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        bSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tOutPut = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bComPort = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tBaudRate = new javax.swing.JTextField();
        bConnect = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        bClearInput = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ComCalc");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(window);
        setMinimumSize(window);
        setName("ComCalc"); // NOI18N
        setPreferredSize(window);
        setResizable(false);
        setSize(window);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calcDisplay.setEditable(false);
        calcDisplay.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        calcDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        calcDisplay.setText("0");
        getContentPane().add(calcDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 340, 50));

        memDisplay.setEditable(false);
        memDisplay.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        memDisplay.setText("NaN");
        getContentPane().add(memDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 340, 60));

        bBack.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bBack.setText("Back");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });
        getContentPane().add(bBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 70, -1));

        bClear.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        bClear.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        getContentPane().add(bClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 70, -1));

        bChange.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        bChange.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bChange.setText("- / +");
        bChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChangeActionPerformed(evt);
            }
        });
        getContentPane().add(bChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        standard.setLayout(new java.awt.GridLayout(4, 4, 5, 5));

        b1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        b1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        standard.add(b1);

        b2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        b2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        standard.add(b2);

        b3.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        b3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        standard.add(b3);

        bPlus.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        bPlus.setText("+");
        bPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlusActionPerformed(evt);
            }
        });
        standard.add(bPlus);

        bSqrt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        bSqrt.setText("√x");
        bSqrt.setActionCommand("sqrt");
        bSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSqrtActionPerformed(evt);
            }
        });
        standard.add(bSqrt);

        b4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        b4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        standard.add(b4);

        b5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        b5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        standard.add(b5);

        b6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        b6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        standard.add(b6);

        bSub.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        bSub.setText("-");
        bSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubActionPerformed(evt);
            }
        });
        standard.add(bSub);

        bSqr.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        bSqr.setText("x²");
        bSqr.setActionCommand("sqr");
        bSqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSqrActionPerformed(evt);
            }
        });
        standard.add(bSqr);

        b7.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        b7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        standard.add(b7);

        b8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        b8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        standard.add(b8);

        b9.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        b9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        standard.add(b9);

        bMulti.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        bMulti.setText("*");
        bMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMultiActionPerformed(evt);
            }
        });
        standard.add(bMulti);

        bPercent.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        bPercent.setText("%");
        bPercent.setActionCommand("percent");
        bPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPercentActionPerformed(evt);
            }
        });
        standard.add(bPercent);

        bKomm.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        bKomm.setText(".");
        bKomm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKommActionPerformed(evt);
            }
        });
        standard.add(bKomm);

        b0.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        b0.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        standard.add(b0);

        bOp.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        bOp.setText("=");
        bOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpActionPerformed(evt);
            }
        });
        standard.add(bOp);

        bDiv.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        bDiv.setText("/");
        bDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDivActionPerformed(evt);
            }
        });
        standard.add(bDiv);

        bPi.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        bPi.setText("π");
        bPi.setActionCommand("3.14159265359");
        bPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPiActionPerformed(evt);
            }
        });
        standard.add(bPi);

        getContentPane().add(standard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 340, 300));

        gCode.setMaximumSize(comBox);
        gCode.setMinimumSize(comBox      );
        gCode.setPreferredSize(comBox);
        gCode.setLayout(new java.awt.BorderLayout(5, 0));

        tInPut.setText("G28");
        tInPut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tInPutActionPerformed(evt);
            }
        });
        gCode.add(tInPut, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(null);

        jLabel3.setText("Output:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(120, 200, 41, 16);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "shorcuts to be implemented" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 70, 240, 110);

        bSend.setText("send");
        jPanel2.add(bSend);
        bSend.setBounds(10, 10, 260, 30);

        tOutPut.setColumns(20);
        tOutPut.setRows(5);
        tOutPut.setMaximumSize(new java.awt.Dimension(232, 200));
        tOutPut.setMinimumSize(new java.awt.Dimension(232, 200));
        tOutPut.setPreferredSize(new java.awt.Dimension(232, 200));
        jScrollPane1.setViewportView(tOutPut);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 260, 180);

        jLabel4.setText("G-Codes");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(120, 50, 50, 16);

        gCode.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setMaximumSize(new java.awt.Dimension(75, 132));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COM Port:");
        jPanel3.add(jLabel1);

        bComPort.setModel(new javax.swing.DefaultComboBoxModel<>(ports));
        bComPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComPortActionPerformed(evt);
            }
        });
        jPanel3.add(bComPort);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BaudRate:");
        jPanel3.add(jLabel2);

        tBaudRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tBaudRate.setText("115200");
        tBaudRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBaudRateActionPerformed(evt);
            }
        });
        jPanel3.add(tBaudRate);

        bConnect.setText("Connect");
        bConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConnectActionPerformed(evt);
            }
        });
        jPanel3.add(bConnect);

        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(bRefresh);

        gCode.add(jPanel3, java.awt.BorderLayout.LINE_START);

        getContentPane().add(gCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 360, 430));

        jToggleButton1.setText("COM");
        jToggleButton1.setPreferredSize(new java.awt.Dimension(50, 100));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 70, 50));

        bClearInput.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bClearInput.setText("Clear Input");
        bClearInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearInputActionPerformed(evt);
            }
        });
        getContentPane().add(bClearInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        if(temp != "")
        {
            if(temp.length() == 1)
            {
                temp = "";
                calcDisplay.setText(temp);
            }
            else
            {
                temp = temp.substring(0, temp.length()-1);
                calcDisplay.setText(temp);
            }
        }
    }//GEN-LAST:event_bBackActionPerformed

    private void bChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChangeActionPerformed
        
        if(temp != "")
        {
            if(temp.charAt(0) == '-')
            {
                temp = temp.substring(1);
                calcDisplay.setText(temp);
            }
            else
            {
                temp = "-".concat(temp);
                calcDisplay.setText(temp);
            }
        }
    }//GEN-LAST:event_bChangeActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        AddDigit(evt);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        AddDigit(evt);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        AddDigit(evt);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        AddDigit(evt);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        AddDigit(evt);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        AddDigit(evt);
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        AddDigit(evt);
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        AddDigit(evt);
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        AddDigit(evt);
    }//GEN-LAST:event_b9ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        if(temp != "")
        {
            AddDigit(evt);
        }
    }//GEN-LAST:event_b0ActionPerformed

    private void bKommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKommActionPerformed
        
        if(!temp.contains("."))
        {
            AddDigit(evt);
        }
    }//GEN-LAST:event_bKommActionPerformed

    private void bPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlusActionPerformed
        if(!"".equals(temp))
        {
            AddDigit(evt);
        }
    }//GEN-LAST:event_bPlusActionPerformed

    private void bSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubActionPerformed
        if(!"".equals(temp))
        {
            AddDigit(evt);
        }
    }//GEN-LAST:event_bSubActionPerformed

    private void bMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMultiActionPerformed
        if(!"".equals(temp))
        {
            AddDigit(evt);
        }
    }//GEN-LAST:event_bMultiActionPerformed

    private void bDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDivActionPerformed
        if(!"".equals(temp))
        {
            AddDigit(evt);
        }
    }//GEN-LAST:event_bDivActionPerformed

    private void bOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpActionPerformed
        if(calc.getOperationList().size() > 1 && temp != "")
        {
            AddDigit(evt);
        }
    }//GEN-LAST:event_bOpActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        temp = ""; 
        calc.clearMemory();
        calcDisplay.setText("");
        memDisplay.setText("");
    }//GEN-LAST:event_bClearActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if ("standard".equals(mode))
        {
            mode = "gCode";
            standard.setVisible(false);
            setSize(windowCom);
            gCode.setVisible(true);
            
        }
        else if("gCode".equals(mode))
        {
            mode = "standard";
            standard.setVisible(true);
            setSize(window);
            gCode.setVisible(false);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void tInPutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tInPutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tInPutActionPerformed

    private void bConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConnectActionPerformed
        if(printer.getConnectionStatus() == false)
        {
            bConnect.setText("Disconnect");
            printer.setPort(0);
            try {
                baudRate = Integer.parseInt(tBaudRate.getText());
            } catch (NumberFormatException e) {
                tBaudRate.setText("115200");
                baudRate = Integer.parseInt(tBaudRate.getText());
            }
            printer.setBaudRate(baudRate);
            
            printer.connect(new SerialPortDataListener() {
                @Override
                public int getListeningEvents() { return SerialPort.LISTENING_EVENT_DATA_AVAILABLE; }
                @Override
                public void serialEvent(SerialPortEvent event)
                {
                    if (event.getEventType() != SerialPort.LISTENING_EVENT_DATA_AVAILABLE)
                        return ;
//                    System.err.println(event);
//                    System.out.print(printer.getSerialData());
                    tOutPut.append(printer.getSerialData());
                }
            });
//            if(!thread2.isAlive())
//            {
//                System.err.println("is now Alive");
//                thread2.start();
//            }
        }
        else
        {
            printer.disconnect();
            bConnect.setText("Connect");
        }
    }//GEN-LAST:event_bConnectActionPerformed

    private void bComPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComPortActionPerformed
        selectedPort = bComPort.getSelectedIndex();
    }//GEN-LAST:event_bComPortActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        
        bComPort.removeAllItems();
        ports = printer.getPortsAsStrings();
        bComPort.setModel(new javax.swing.DefaultComboBoxModel<>(ports));
        
    }//GEN-LAST:event_bRefreshActionPerformed

    private void tBaudRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBaudRateActionPerformed
        
    }//GEN-LAST:event_tBaudRateActionPerformed

    private void bSqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSqrActionPerformed
        AddDigit(evt);
    }//GEN-LAST:event_bSqrActionPerformed

    private void bPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPercentActionPerformed
        AddDigit(evt);
    }//GEN-LAST:event_bPercentActionPerformed

    private void bSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSqrtActionPerformed
        AddDigit(evt);
    }//GEN-LAST:event_bSqrtActionPerformed

    private void bPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPiActionPerformed
        AddDigit(evt);
    }//GEN-LAST:event_bPiActionPerformed

    private void bClearInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearInputActionPerformed
        temp = ""; 
        calcDisplay.setText(temp);
        
    }//GEN-LAST:event_bClearInputActionPerformed
 
    private void AddDigit(java.awt.event.ActionEvent evt)
    {
        String memTemp = "";
        String input = evt.getActionCommand();
        if(Arrays.asList( numberPad ).contains( input ))
        {
            temp += input;
//            System.out.println(temp);
            calcDisplay.setText(temp);
        }
        else if(Arrays.asList(opPad).contains(input))
        {
            calc.addOperation(temp);
            temp = "";
            calcDisplay.setText("0");
            calc.addOperation(input);
            if("=".equals(input))
            {
                calcDisplay.setText(Double.toString(calc.execInception(0)).replaceAll("\\.0+$", ""));
                calc.clearMemory();
            }
        }
        else if(Arrays.asList(specialConst).contains(input))
        {
            temp = input;
            calcDisplay.setText(temp);
        }
        else if(Arrays.asList(specialOp).contains(input))
        {
            if("sqr".equals(input))
            {
                temp = String.format("%s",Math.pow(Double.parseDouble(calcDisplay.getText()),2)).replaceAll("\\.0+$", "");
            }
            else if("sqrt".equals(input))
            {
                temp = String.format("%s",Math.sqrt(Double.parseDouble(calcDisplay.getText()))).replaceAll("\\.0+$", "");
            }
            else if("percent".equals(input))
            {
                temp = String.format("%s",(Double.parseDouble(calcDisplay.getText()))* 0.01).replaceAll("\\.0+$", "");
            }
            calcDisplay.setText(temp);
            
        }
        for(String s : calc.getOperationList())
        {
            memTemp += s;
        }
            memDisplay.setText(memTemp);            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                System.out.println(info.getClassName());
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bChange;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bClearInput;
    private javax.swing.JComboBox<String> bComPort;
    private javax.swing.JButton bConnect;
    private javax.swing.JButton bDiv;
    private javax.swing.JButton bKomm;
    private javax.swing.JButton bMulti;
    private javax.swing.JButton bOp;
    private javax.swing.JButton bPercent;
    private javax.swing.JButton bPi;
    private javax.swing.JButton bPlus;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bSend;
    private javax.swing.JButton bSqr;
    private javax.swing.JButton bSqrt;
    private javax.swing.JButton bSub;
    private javax.swing.JTextField calcDisplay;
    private javax.swing.JPanel gCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField memDisplay;
    private javax.swing.JPanel standard;
    private javax.swing.JTextField tBaudRate;
    private javax.swing.JTextField tInPut;
    private javax.swing.JTextArea tOutPut;
    // End of variables declaration//GEN-END:variables
}
